### ISSUE TITLE
2.3.1

### ISSUE THREAD

**Issue by JulienSTC** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#187] opened 2023-05-16 18:05 UTC
Data received from SME, Excel in data gap folder

**Comment by MaiaPelletier** [comment] 2023-05-16 19:45
this was already completed in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/ac477a5e8148541ad358b6d3ee2c150931a6abba (duplicate of #184 )

**Closed by MaiaPelletier** 2023-05-16 19:45 UTC
Labels: data-update
